### PR TITLE
Adding the basics of sovereign cloud support.

### PR DESCRIPTION
**Pull request by petkahl**
Also includes one case where there was additional data at the end of an
environment variable, so added a sed command to remove it.

### CODE REVIEW

**Review by hallihan — COMMENTED** [review]
Thanks for the suggestions.  I think this might be better if we use the endpoint suffix from [`environment().suffixes.storage`](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-deployment#environment).  See the results of this query for several examples: <https://github.com/Azure/azure-quickstart-templates/search?q=environment%28%29.suffixes.storage&unscoped_q=environment%28%29.suffixes.storage>.  This way the end user doesn't have to know or provide the value.

**Comment by ckittel** [comment]
How's the update/testing coming along @petkahl?

**Comment by petkahl** [comment]
I'll get it done today.

**Comment by hallihan** [comment]
There are several more connection strings that do not currently have an endpoint suffix parameters, you can find them by running ```grep -rn "AccountName=" * | grep -v "environment()"``` in the local directory where you have cloned the repo.

Also, the diff is a bit cluttered.  It looks like you merged in the latest changes from the default branch, but it would probably be better to rebase.  If you have the remote for the  mspnp/serverless-reference-implementation repo set as 'upstream' then you can do ```git rebase -i upstream/master```.  This will open up an editor with some instructions showing how you can combine or drop commits from your branch.

**Comment by petkahl** [comment]
need to reopen PR because I had to delete/recreate the branch to fix my merge screw-up. However, it doesn't seem to want to let me. The branch is there again, assuming I didn't misspell it.

**Pull request closed without merging**
